### ISSUE TITLE
Better handle connection errors

### ISSUE THREAD

**Issue by mpdehaan** [opsmop/opsmop#79]
When trying to connect to a system that is *not there* the connection can take about 10 seconds to time out - this is completely fine, but the output is exceptionally verbose.

We should catch these exceptions and produce cleaner messages:
(env) llamaforge:opsmop-demo michaeldehaan$ PYTHONPATH=~/Devel/opsmop python3 content/push_demo.py --push --apply

Role: WebServers

Traceback (most recent call last):

  File "/Users/michaeldehaan/Devel/opsmop/env/lib/python3.7/site-packages/mitogen/parent.py", line 1841, in _connect
    stream.connect()
  File "/Users/michaeldehaan/Devel/opsmop/env/lib/python3.7/site-packages/mitogen/ssh.py", line 237, in connect
    super(Stream, self).connect()
  File "/Users/michaeldehaan/Devel/opsmop/env/lib/python3.7/site-packages/mitogen/parent.py", line 1195, in connect
    self._connect_bootstrap()
  File "/Users/michaeldehaan/Devel/opsmop/env/lib/python3.7/site-packages/mitogen/ssh.py", line 307, in _connect_bootstrap
    self._connect_input_loop(it)
  File "/Users/michaeldehaan/Devel/opsmop/env/lib/python3.7/site-packages/mitogen/ssh.py", line 269, in _connect_input_loop
    for buf, partial in filter_debug(self, it):
  File "/Users/michaeldehaan/Devel/opsmop/env/lib/python3.7/site-packages/mitogen/ssh.py", line 85, in filter_debug
    for chunk in it:
  File "/Users/michaeldehaan/Devel/opsmop/env/lib/python3.7/site-packages/mitogen/parent.py", line 515, in iter_read
    raise mitogen.core.TimeoutError('read timed out')
mitogen.core.TimeoutError: read timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "content/push_demo.py", line 101, in <module>
    Cli(Demo())
  File "/Users/michaeldehaan/Devel/opsmop/opsmop/client/cli.py", line 50, in __init__
    self.go()
  File "/Users/michaeldehaan/Devel/opsmop/opsmop/client/cli.py", line 127, in go
    api.apply()
  File "/Users/michaeldehaan/Devel/opsmop/opsmop/core/api.py", line 69, in apply
    contexts = executor.apply()
  File "/Users/michaeldehaan/Devel/opsmop/opsmop/core/executor.py", line 77, in apply
    self.run_all_policies(mode=APPLY)
  File "/Users/michaeldehaan/Devel/opsmop/opsmop/core/executor.py", line 89, in run_all_policies
    self.run_policy(policy=policy)
  File "/Users/michaeldehaan/Devel/opsmop/opsmop/core/executor.py", line 106, in run_policy
    self.process_remote_role(policy, role)
  File "/Users/michaeldehaan/Devel/opsmop/opsmop/core/executor.py", line 169, in process_remote_role
    self.connect_to_all_hosts(hosts, role, max_workers)
  File "/Users/michaeldehaan/Devel/opsmop/opsmop/core/executor.py", line 126, in connect_to_all_hosts
    batch.apply_async(host_connector, max_workers=max_workers)
  File "/Users/michaeldehaan/Devel/opsmop/opsmop/push/batch.py", line 48, in apply_async
    data = future.result()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/michaeldehaan/Devel/opsmop/opsmop/core/executor.py", line 125, in host_connector
    self.connection_manager.connect(host, role)
  File "/Users/michaeldehaan/Devel/opsmop/opsmop/push/connections.py", line 139, in connect
    conn = self.get_connection_for_host(host, role)
  File "/Users/michaeldehaan/Devel/opsmop/opsmop/push/connections.py", line 110, in get_connection_for_host
    return self._form_connection(host, role)
  File "/Users/michaeldehaan/Devel/opsmop/opsmop/push/connections.py", line 127, in _form_connection
    via=parent
  File "/Users/michaeldehaan/Devel/opsmop/env/lib/python3.7/site-packages/mitogen/parent.py", line 1909, in ssh
    return self.connect(u'ssh', **kwargs)
  File "/Users/michaeldehaan/Devel/opsmop/env/lib/python3.7/site-packages/mitogen/parent.py", line 1858, in connect
    return self._connect(klass, name=name, **kwargs)
  File "/Users/michaeldehaan/Devel/opsmop/env/lib/python3.7/site-packages/mitogen/parent.py", line 1843, in _connect
    raise mitogen.core.StreamError(self.connection_timeout_msg)
mitogen.core.StreamError: Connection timed out.

**Comment by mpdehaan** [comment]
Related to #84
