### ISSUE TITLE
python 3.7 - mitogen importer tracebacks in push mode

### ISSUE THREAD

**Issue by mpdehaan** [opsmop/opsmop#80]
Usage of push mode from a python 3.7 master control machine will result in some tracebacks related to the importer code.

I've shared this with @dw and need to dig in to see if there's something we can do to hack around this on the opsmop side or what.

For those encountering this, you should *not* see a problem on earlier pythons.

**Comment by mpdehaan** [comment]
Selection from mitogen.utils.log_to_file()

12:34:51.481700 D mitogen.ctx.local.72181: mitogen: ModuleForwarder(Router(Broker(0x10808ee48)))._on_get_module(Message(1, 4, 4, 100, 0, b'__main__'..8))
12:34:51.481799 D mitogen: ModuleResponder(Router(Broker(0x104c59128)))._on_get_module(b'__main__')
12:34:51.481946 D mitogen: ModuleFinder()._get_module_via_pkgutil('__main__'): Error while finding loader for '__main__' (<class 'ValueError'>: __main__.__spec__ is None)
12:34:51.482020 D mitogen: _get_module_via_sys_modules('__main__') -> <module '__main__' from 'content/push_demo.py'>
12:34:51.482239 D mitogen: While importing '__main__'
Traceback (most recent call last):
  File "/Users/michaeldehaan/Devel/opsmop/env/lib/python3.7/site-packages/mitogen/master.py", line 694, in _send_module_and_related
    tup = self._build_tuple(fullname)
  File "/Users/michaeldehaan/Devel/opsmop/env/lib/python3.7/site-packages/mitogen/master.py", line 636, in _build_tuple
    path, source, is_pkg = self._finder.get_module_source(fullname)
  File "/Users/michaeldehaan/Devel/opsmop/env/lib/python3.7/site-packages/mitogen/master.py", line 472, in get_module_source
    tup = method(self, fullname)
  File "/Users/michaeldehaan/Devel/opsmop/env/lib/python3.7/site-packages/mitogen/master.py", line 441, in _get_module_via_sys_modules
    source = inspect.getsource(module)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py", line 968, in getsource
    lines, lnum = getsourcelines(object)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py", line 955, in getsourcelines
    lines, lnum = findsource(object)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py", line 786, in findsource
    raise OSError('could not get source code')
OSError: could not get source code
12:34:51.483333 D mitogen.ctx.ssh.192.168.48.143.sudo.root: mitogen: Importer(): 'asyncio.subprocess' is submodule of a package we did not load
12:34:51.483427 D mitogen.ctx.ssh.192.168.48.143.sudo.root: mitogen: Importer(): 'asyncio.transports' is submodule of a package we did not load
12:34:51.483510 D mitogen.ctx.ssh.192.168.48.143.sudo.root: mitogen: Importer(): 'asyncio.unix_events' is submodule of a package we did not load
12:34:51.483867 D mitogen.ctx.local.72181: mitogen: ModuleForwarder(Router(Broker(0x10808ee48)))._on_get_module(): sending '__main__'
12:34:51.483992 D mitogen.ctx.ssh.192.168.48.143.sudo.root: mitogen: Importer(): 'asyncio.base_subprocess' is submodule of a package we did not load

It's been suggested that I dig around in linecache.py in the python3 source code to see where it might be dying

**Comment by dw** [comment]
I will try to have a look at this tomorrow and figure out what is wrong with `_get_module_via_pkgutil`

**Comment by dw** [comment]
Should everything be checked in necessary to reproduce that inspect.getsource() error? It looks like in the new world it was too complicated to have `__main__` be 'just another module' and `pkgutil` is broken for it permanently now.

**Comment by dw** [comment]
On first attempt:

````
Traceback (most recent call last):
  File "demo/content/push_demo.py", line 113, in <module>
    Cli(Demo())
  File "/home/dmw/src/opsmop/opsmop/core/policy.py", line 33, in __init__
    self.setup(extra_variables=original, **common)
  File "/home/dmw/src/opsmop/opsmop/core/resource.py", line 41, in setup
    self._field_spec.load_parameters(self)
  File "/home/dmw/src/opsmop/opsmop/core/fields.py", line 91, in load_parameters
    field.load(obj, k)
  File "/home/dmw/src/opsmop/opsmop/core/field.py", line 176, in load
    v = self._get_coerced_resource_value(obj, k)
  File "/home/dmw/src/opsmop/opsmop/core/field.py", line 89, in _get_coerced_resource_value
    v = self.loader()
  File "demo/content/push_demo.py", line 98, in set_roles
    WebServers(name='webservers', tag='webservers'),
  File "/home/dmw/src/opsmop/opsmop/core/role.py", line 36, in __init__
    self.setup(extra_variables=original, **common)
  File "/home/dmw/src/opsmop/opsmop/core/resource.py", line 41, in setup
    self._field_spec.load_parameters(self)
  File "/home/dmw/src/opsmop/opsmop/core/fields.py", line 91, in load_parameters
    field.load(obj, k)
  File "/home/dmw/src/opsmop/opsmop/core/field.py", line 176, in load
    v = self._get_coerced_resource_value(obj, k)
  File "/home/dmw/src/opsmop/opsmop/core/field.py", line 89, in _get_coerced_resource_value
    v = self.loader()
  File "demo/content/push_demo.py", line 35, in set_resources
    Debug(),
NameError: name 'Debug' is not defined
````

After removing `Debug()`, I get:

````
Traceback (most recent call last):
  File "demo/content/push_demo.py", line 112, in <module>
    Cli(Demo())
  File "/home/dmw/src/opsmop/opsmop/core/policy.py", line 33, in __init__
    self.setup(extra_variables=original, **common)
  File "/home/dmw/src/opsmop/opsmop/core/resource.py", line 41, in setup
    self._field_spec.load_parameters(self)
  File "/home/dmw/src/opsmop/opsmop/core/fields.py", line 91, in load_parameters
    field.load(obj, k)
  File "/home/dmw/src/opsmop/opsmop/core/field.py", line 176, in load
    v = self._get_coerced_resource_value(obj, k)
  File "/home/dmw/src/opsmop/opsmop/core/field.py", line 89, in _get_coerced_resource_value
    v = self.loader()
  File "demo/content/push_demo.py", line 97, in set_roles
    WebServers(name='webservers', tag='webservers'),
  File "/home/dmw/src/opsmop/opsmop/core/role.py", line 36, in __init__
    self.setup(extra_variables=original, **common)
  File "/home/dmw/src/opsmop/opsmop/core/resource.py", line 41, in setup
    self._field_spec.load_parameters(self)
  File "/home/dmw/src/opsmop/opsmop/core/fields.py", line 91, in load_parameters
    field.load(obj, k)
  File "/home/dmw/src/opsmop/opsmop/core/field.py", line 176, in load
    v = self._get_coerced_resource_value(obj, k)
  File "/home/dmw/src/opsmop/opsmop/core/field.py", line 89, in _get_coerced_resource_value
    v = self.loader()
  File "demo/content/push_demo.py", line 35, in set_resources
    File("/tmp/foo3.txt", from_content="Hey!", signals='evt_01'),
  File "/home/dmw/src/opsmop/opsmop/types/file.py", line 24, in __init__
    self.setup(name=name, **kwargs)
  File "/home/dmw/src/opsmop/opsmop/core/resource.py", line 40, in setup
    self._field_spec.find_unexpected_keys(self)
  File "/home/dmw/src/opsmop/opsmop/core/fields.py", line 78, in find_unexpected_keys
    raise Exception("%s: parameter is not understood, %s" % (self, k))
Exception: <opsmop.core.fields.Fields object at 0x7f5ce9b920b8>: parameter is not understood, signals

````

**Comment by mpdehaan** [comment]
Seems like I missed checking an update in, I’ll be back w my desktop shortly and will take a look at what may not be pushed. Sorry about that!

**Comment by dw** [comment]
np :)

**Comment by mpdehaan** [comment]
I should clarify after making this change I've *never* run it successfully (so there could be other errors in my code once getting past the import error - or running it on *another* python), but in my case, it's a good way to reproduce the above traceback.

**Comment by dw** [comment]
>:O   damn users can't even rtfd! Thanks, looking at it now

**Comment by dw** [comment]
![screenshot from 2019-01-23 19-40-58](https://user-images.githubusercontent.com/2315/51632323-ee700000-1f46-11e9-941c-29916e6e51d0.png)

Hrm.. is your push_demo.py definitely the same one as in the repo?

**Comment by mpdehaan** [comment]
Hmmmmmm.... this is 3.7.0 on OS X as the master machine targetting python 3.6.6 on the remote (Ubuntu 18.04).  Currently upgrading python on the master to see if that makes a difference.

**Comment by mpdehaan** [comment]
(Also, yes)

**Comment by dw** [comment]
I'll try under OS X homebrew Python

**Comment by mpdehaan** [comment]
Ok so sorry for the goose chase, rebuilding it myself to 3.7.2 and running OUTSIDE the virtualenv cleared this up completely.  I have no idea what was going on, but it's probably safe to say it could be a Python 3.7.0/1 issue.  

I suspect no one is going to hit this.

Thanks for helping to look!

**Comment by dw** [comment]
Nice :)  There is still a bug with `__main__` falling back to inspect.getsource() in the first place, I'll keep that ticket open and hopefully sort it after the next release
